/* SOL Lab Biology: the 2018 Virginia Biology Standards of Learning (BIO.1 to BIO.8) and their key ideas (BIO.8.a), with
   the text the teacher page's standards report shows for each (tools/teacher/teacher.js reads window.SolStandards).
   GENERATED by node tools/make-standards-bio.js from the standards map in js/content.js: edit that map and rebuild. */
(function (root) {
  "use strict";
  var STANDARDS = {
 "BIO.1": {
  "text": "Standard BIO.1: Scientific investigation.",
  "skills": []
 },
 "BIO.1.a": {
  "text": "Scientific investigation: Asking questions and defining problems.",
  "skills": []
 },
 "BIO.1.b": {
  "text": "Scientific investigation: Planning and carrying out investigations.",
  "skills": []
 },
 "BIO.1.c": {
  "text": "Scientific investigation: Interpreting, analyzing, and evaluating data.",
  "skills": []
 },
 "BIO.1.d": {
  "text": "Scientific investigation: Constructing and critiquing conclusions and explanations.",
  "skills": []
 },
 "BIO.1.e": {
  "text": "Scientific investigation: Developing and using models.",
  "skills": []
 },
 "BIO.1.f": {
  "text": "Scientific investigation: Obtaining, evaluating, and communicating information.",
  "skills": []
 },
 "BIO.2": {
  "text": "Standard BIO.2: Chemical and biochemical processes.",
  "skills": []
 },
 "BIO.2.a": {
  "text": "Chemical and biochemical processes: Water chemistry and its impact on life processes.",
  "skills": []
 },
 "BIO.2.b": {
  "text": "Chemical and biochemical processes: The structure and function of macromolecules.",
  "skills": []
 },
 "BIO.2.c": {
  "text": "Chemical and biochemical processes: The nature of enzymes.",
  "skills": []
 },
 "BIO.2.d": {
  "text": "Chemical and biochemical processes: Protein synthesis: DNA as the code for proteins.",
  "skills": []
 },
 "BIO.2.e": {
  "text": "Chemical and biochemical processes: The capture, storage, transformation, and flow of energy through photosynthesis and respiration.",
  "skills": []
 },
 "BIO.3": {
  "text": "Standard BIO.3: Cell structure and function.",
  "skills": []
 },
 "BIO.3.a": {
  "text": "Cell structure and function: The cell theory is supported by evidence.",
  "skills": []
 },
 "BIO.3.b": {
  "text": "Cell structure and function: Structures in unicellular and multicellular organisms work interdependently to carry out life processes.",
  "skills": []
 },
 "BIO.3.c": {
  "text": "Cell structure and function: The structure and function of the cell membrane support cell transport.",
  "skills": []
 },
 "BIO.3.d": {
  "text": "Cell structure and function: Specialization leads to the development of different types of cells.",
  "skills": []
 },
 "BIO.4": {
  "text": "Standard BIO.4: Bacteria and viruses.",
  "skills": []
 },
 "BIO.4.a": {
  "text": "Bacteria and viruses: Viruses depend on a host for metabolic processes.",
  "skills": []
 },
 "BIO.4.b": {
  "text": "Bacteria and viruses: The modes of reproduction and replication can be compared.",
  "skills": []
 },
 "BIO.4.c": {
  "text": "Bacteria and viruses: The structures and functions can be compared.",
  "skills": []
 },
 "BIO.4.d": {
  "text": "Bacteria and viruses: Bacteria and viruses have a role in other organisms and the environment.",
  "skills": []
 },
 "BIO.4.e": {
  "text": "Bacteria and viruses: The germ theory of infectious disease is supported by evidence.",
  "skills": []
 },
 "BIO.5": {
  "text": "Standard BIO.5: Mechanisms of inheritance.",
  "skills": []
 },
 "BIO.5.a": {
  "text": "Mechanisms of inheritance: DNA has structure and is the foundation for protein synthesis.",
  "skills": []
 },
 "BIO.5.b": {
  "text": "Mechanisms of inheritance: The structural model of DNA has developed over time.",
  "skills": []
 },
 "BIO.5.c": {
  "text": "Mechanisms of inheritance: Cell division and gamete formation pass genes to the next generation.",
  "skills": []
 },
 "BIO.5.d": {
  "text": "Mechanisms of inheritance: The variety of traits in an organism are the result of the expression of various combinations of alleles.",
  "skills": []
 },
 "BIO.5.e": {
  "text": "Mechanisms of inheritance: Mutations and genetic variation.",
  "skills": []
 },
 "BIO.5.f": {
  "text": "Mechanisms of inheritance: Synthetic biology has biological and ethical implications.",
  "skills": []
 },
 "BIO.6": {
  "text": "Standard BIO.6: Modern classification.",
  "skills": []
 },
 "BIO.6.a": {
  "text": "Modern classification: Structural similarities among organisms.",
  "skills": []
 },
 "BIO.6.b": {
  "text": "Modern classification: Fossil record interpretation.",
  "skills": []
 },
 "BIO.6.c": {
  "text": "Modern classification: Comparison of developmental stages.",
  "skills": []
 },
 "BIO.6.d": {
  "text": "Modern classification: Biochemical similarities and differences.",
  "skills": []
 },
 "BIO.6.e": {
  "text": "Modern classification: Classification systems are adaptable to new scientific discoveries.",
  "skills": []
 },
 "BIO.7": {
  "text": "Standard BIO.7: Populations change through time.",
  "skills": []
 },
 "BIO.7.a": {
  "text": "Populations change through time: Evidence found in fossil records.",
  "skills": []
 },
 "BIO.7.b": {
  "text": "Populations change through time: How variation of traits, reproductive strategies, and environmental pressures affect survival.",
  "skills": []
 },
 "BIO.7.c": {
  "text": "Populations change through time: How natural selection leads to adaptations.",
  "skills": []
 },
 "BIO.7.d": {
  "text": "Populations change through time: The emergence of new species.",
  "skills": []
 },
 "BIO.7.e": {
  "text": "Populations change through time: Scientific evidence and explanations for biological evolution.",
  "skills": []
 },
 "BIO.8": {
  "text": "Standard BIO.8: Dynamic equilibria in ecosystems.",
  "skills": []
 },
 "BIO.8.a": {
  "text": "Dynamic equilibria in ecosystems: Interactions within and among populations: carrying capacity, limiting factors, and growth curves.",
  "skills": []
 },
 "BIO.8.b": {
  "text": "Dynamic equilibria in ecosystems: Nutrient cycling with energy flow through ecosystems.",
  "skills": []
 },
 "BIO.8.c": {
  "text": "Dynamic equilibria in ecosystems: Succession patterns in ecosystems.",
  "skills": []
 },
 "BIO.8.d": {
  "text": "Dynamic equilibria in ecosystems: Natural events and human activities influence local and global ecosystems and the flora and fauna of Virginia.",
  "skills": []
 }
};
  var SKILL = {};
  Object.keys(STANDARDS).forEach(function (code) { STANDARDS[code].skills.forEach(function (s) { SKILL[s.id] = { code: code, text: s.text, level: s.level }; }); });
  var api = { STANDARDS: STANDARDS, SKILL: SKILL };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.SolStandards = api;
})(typeof window !== "undefined" ? window : (typeof globalThis !== "undefined" ? globalThis : this));
