/* SOL Lab Algebra I: the 2023 Virginia Algebra I Standards of Learning the game reviews, for the teacher screen's
   standards report (the SOL Labyrinth backbone's js/standards-<game>.js, v5.17). GENERATED by tools/build-standards.js
   from HEIST_STANDARDS in js/content.js: edit there and rebuild. A standard's skills are its lettered statements, each
   LOTS (lower-order: translate, evaluate, simplify, factor, solve, graph, write) or HOTS (higher-order: analyze,
   compare, justify, verify, investigate, interpret in context, draw conclusions). */
(function (root) {
  "use strict";
  var STANDARDS = {
 "A.EO.1": {
  "text": "Expressions: represent and evaluate",
  "skills": [
   {
    "id": "A.EO.1.a",
    "text": "translate between verbal quantitative situations and algebraic expressions, including contextual situations",
    "level": "LOTS"
   },
   {
    "id": "A.EO.1.b",
    "text": "evaluate algebraic expressions which include absolute value, square roots, and cube roots for given replacement values to include rational numbers, without rationalizing the denominator",
    "level": "LOTS"
   }
  ]
 },
 "A.EO.2": {
  "text": "Polynomials: operations and factoring",
  "skills": [
   {
    "id": "A.EO.2.a",
    "text": "determine sums and differences of polynomial expressions in one variable, using a variety of strategies, including concrete objects and their related pictorial and symbolic models",
    "level": "LOTS"
   },
   {
    "id": "A.EO.2.b",
    "text": "determine the product of polynomial expressions in one variable, using a variety of strategies, including the distributive property and area models; factors limited to five or fewer terms",
    "level": "LOTS"
   },
   {
    "id": "A.EO.2.c",
    "text": "factor completely first- and second-degree polynomials in one variable with integral coefficients; after factoring out the GCF, leading coefficients have no more than four factors",
    "level": "LOTS"
   },
   {
    "id": "A.EO.2.d",
    "text": "determine the quotient of polynomials, using a monomial or binomial divisor, or a completely factored divisor",
    "level": "LOTS"
   },
   {
    "id": "A.EO.2.e",
    "text": "represent and demonstrate equality of quadratic expressions in different forms (concrete, verbal, symbolic, and graphical)",
    "level": "LOTS"
   }
  ]
 },
 "A.EO.3": {
  "text": "Laws of exponents",
  "skills": [
   {
    "id": "A.EO.3.a",
    "text": "derive the laws of exponents through explorations of patterns, to include products, quotients, and powers of bases",
    "level": "HOTS"
   },
   {
    "id": "A.EO.3.b",
    "text": "simplify multivariable expressions and ratios of monomial expressions in which the exponents are integers, using the laws of exponents",
    "level": "LOTS"
   }
  ]
 },
 "A.EO.4": {
  "text": "Radical expressions",
  "skills": [
   {
    "id": "A.EO.4.a",
    "text": "simplify and determine equivalent radical expressions involving the square root of a whole number in simplest form",
    "level": "LOTS"
   },
   {
    "id": "A.EO.4.b",
    "text": "simplify and determine equivalent radical expressions involving the cube root of an integer",
    "level": "LOTS"
   },
   {
    "id": "A.EO.4.c",
    "text": "add, subtract, and multiply radicals, limited to numeric square and cube root expressions",
    "level": "LOTS"
   },
   {
    "id": "A.EO.4.d",
    "text": "generate equivalent numerical expressions and justify their equivalency for radicals using rational exponents, limited to rational exponents of 1/2 and 1/3",
    "level": "HOTS"
   }
  ]
 },
 "A.EI.1": {
  "text": "Linear equations and inequalities in one variable",
  "skills": [
   {
    "id": "A.EI.1.a",
    "text": "write a linear equation or inequality in one variable to represent a contextual situation",
    "level": "LOTS"
   },
   {
    "id": "A.EI.1.b",
    "text": "solve multistep linear equations in one variable, including those in contextual situations, by applying the properties of real numbers and/or properties of equality",
    "level": "LOTS"
   },
   {
    "id": "A.EI.1.c",
    "text": "solve multistep linear inequalities in one variable algebraically and graph the solution set on a number line, including those in contextual situations, by applying the properties of real numbers and/or properties of inequality",
    "level": "LOTS"
   },
   {
    "id": "A.EI.1.d",
    "text": "rearrange a formula or literal equation to solve for a specified variable by applying the properties of equality",
    "level": "LOTS"
   },
   {
    "id": "A.EI.1.e",
    "text": "determine if a linear equation in one variable has one solution, no solution, or an infinite number of solutions",
    "level": "LOTS"
   },
   {
    "id": "A.EI.1.f",
    "text": "verify possible solution(s) to multistep linear equations and inequalities in one variable algebraically, graphically, and with technology to justify the reasonableness of the answer(s); explain the solution method and interpret solutions in context",
    "level": "HOTS"
   }
  ]
 },
 "A.EI.2": {
  "text": "Systems of linear equations and inequalities",
  "skills": [
   {
    "id": "A.EI.2.a",
    "text": "create a system of two linear equations in two variables to represent a contextual situation",
    "level": "LOTS"
   },
   {
    "id": "A.EI.2.b",
    "text": "apply the properties of real numbers and/or properties of equality to solve a system of two linear equations in two variables, algebraically and graphically",
    "level": "LOTS"
   },
   {
    "id": "A.EI.2.c",
    "text": "determine whether a system of two linear equations has one solution, no solution, or an infinite number of solutions",
    "level": "HOTS"
   },
   {
    "id": "A.EI.2.d",
    "text": "create a linear inequality in two variables to represent a contextual situation",
    "level": "LOTS"
   },
   {
    "id": "A.EI.2.e",
    "text": "represent the solution of a linear inequality in two variables graphically on a coordinate plane",
    "level": "LOTS"
   },
   {
    "id": "A.EI.2.f",
    "text": "create a system of two linear inequalities in two variables to represent a contextual situation",
    "level": "LOTS"
   },
   {
    "id": "A.EI.2.g",
    "text": "represent the solution set of a system of two linear inequalities in two variables graphically on a coordinate plane",
    "level": "LOTS"
   },
   {
    "id": "A.EI.2.h",
    "text": "verify possible solution(s) to a system of two linear equations, a linear inequality in two variables, or a system of two linear inequalities algebraically, graphically, and with technology to justify the reasonableness of the answer(s); explain the solution method and interpret solutions in context",
    "level": "HOTS"
   }
  ]
 },
 "A.EI.3": {
  "text": "Quadratic equations in one variable",
  "skills": [
   {
    "id": "A.EI.3.a",
    "text": "solve a quadratic equation in one variable over the set of real numbers with rational or irrational solutions, including those that can be used to solve contextual problems",
    "level": "LOTS"
   },
   {
    "id": "A.EI.3.b",
    "text": "determine and justify if a quadratic equation in one variable has no real solutions, one real solution, or two real solutions",
    "level": "HOTS"
   },
   {
    "id": "A.EI.3.c",
    "text": "verify possible solution(s) to a quadratic equation in one variable algebraically, graphically, and with technology to justify the reasonableness of answer(s); explain the solution method and interpret solutions for problems given in context",
    "level": "HOTS"
   }
  ]
 },
 "A.F.1": {
  "text": "Linear functions",
  "skills": [
   {
    "id": "A.F.1.a",
    "text": "determine and identify the domain, range, zeros, slope, and intercepts of a linear function, presented algebraically or graphically, including the interpretation of these characteristics in contextual situations",
    "level": "LOTS"
   },
   {
    "id": "A.F.1.b",
    "text": "investigate and explain how transformations to the parent function y = x affect the rate of change (slope) and the y-intercept of a linear function",
    "level": "HOTS"
   },
   {
    "id": "A.F.1.c",
    "text": "write equivalent algebraic forms of linear functions, including slope-intercept form, standard form, and point-slope form, and analyze and interpret the information revealed by each form",
    "level": "HOTS"
   },
   {
    "id": "A.F.1.d",
    "text": "write the equation of a linear function to model a linear relationship between two quantities, including contextual situations: given the graph of a line, two points with integer coordinates, or the slope and a point; vertical lines as x = a and horizontal lines as y = c",
    "level": "LOTS"
   },
   {
    "id": "A.F.1.e",
    "text": "write the equation of a line parallel or perpendicular to a given line through a given point",
    "level": "LOTS"
   },
   {
    "id": "A.F.1.f",
    "text": "graph a linear function in two variables, with and without the use of technology, including those that can represent contextual situations",
    "level": "LOTS"
   },
   {
    "id": "A.F.1.g",
    "text": "for any value x in the domain of f, determine f(x), and determine x given any value f(x) in the range of f, given an algebraic or graphical representation of a linear function",
    "level": "LOTS"
   },
   {
    "id": "A.F.1.h",
    "text": "compare and contrast the characteristics of linear functions represented algebraically, graphically, in tables, and in contextual situations",
    "level": "HOTS"
   }
  ]
 },
 "A.F.2": {
  "text": "Quadratic and exponential functions",
  "skills": [
   {
    "id": "A.F.2.a",
    "text": "determine whether a relation, represented by a set of ordered pairs, a table, a mapping, or a graph is a function",
    "level": "HOTS"
   },
   {
    "id": "A.F.2.b",
    "text": "given an equation or graph, determine key characteristics of a quadratic function including x-intercepts (zeros), y-intercept, vertex (maximum or minimum), and domain and range (including when restricted by context); interpret key characteristics in contextual situations",
    "level": "LOTS"
   },
   {
    "id": "A.F.2.c",
    "text": "graph a quadratic function f(x) in two variables using a variety of strategies, including transformations f(x) + k and kf(x), where k is limited to rational values",
    "level": "LOTS"
   },
   {
    "id": "A.F.2.d",
    "text": "make connections between the algebraic (standard and factored forms) and graphical representation of a quadratic function",
    "level": "HOTS"
   },
   {
    "id": "A.F.2.e",
    "text": "given an equation or graph of an exponential function in the form y = ab^x (where b is limited to a natural number), interpret key characteristics, including y-intercepts and domain and range; interpret key characteristics in contextual situations",
    "level": "LOTS"
   },
   {
    "id": "A.F.2.f",
    "text": "graph an exponential function f(x) in two variables using a variety of strategies, including transformations f(x) + k and kf(x), where k is limited to rational values",
    "level": "LOTS"
   },
   {
    "id": "A.F.2.g",
    "text": "for any value x in the domain of f, determine f(x) of a quadratic or exponential function; determine x given any value f(x) in the range of f of a quadratic function; explain the meaning of x and f(x) in context",
    "level": "HOTS"
   },
   {
    "id": "A.F.2.h",
    "text": "compare and contrast the key characteristics of linear functions (f(x) = x), quadratic functions (f(x) = x²), and exponential functions (f(x) = bˣ) using tables and graphs",
    "level": "HOTS"
   }
  ]
 },
 "A.ST.1": {
  "text": "The data cycle with bivariate data",
  "skills": [
   {
    "id": "A.ST.1.a",
    "text": "formulate investigative questions that require the collection or acquisition of bivariate data",
    "level": "HOTS"
   },
   {
    "id": "A.ST.1.b",
    "text": "determine what variables could be used to explain a given contextual problem or situation or answer investigative questions",
    "level": "HOTS"
   },
   {
    "id": "A.ST.1.c",
    "text": "determine an appropriate method to collect a representative sample (survey, observation, or experiment) to answer an investigative question",
    "level": "HOTS"
   },
   {
    "id": "A.ST.1.d",
    "text": "given a table of ordered pairs or a scatterplot representing no more than 30 data points, use available technology to determine whether a linear or quadratic function would represent the relationship, and if so, determine the equation of the curve of best fit",
    "level": "HOTS"
   },
   {
    "id": "A.ST.1.e",
    "text": "use linear and quadratic regression methods available through technology to write a linear or quadratic function that represents the data where appropriate and describe the strengths and weaknesses of the model",
    "level": "HOTS"
   },
   {
    "id": "A.ST.1.f",
    "text": "use a linear model to predict outcomes and evaluate the strength and validity of these predictions, including through the use of technology",
    "level": "HOTS"
   },
   {
    "id": "A.ST.1.g",
    "text": "investigate and explain the meaning of the rate of change (slope) and y-intercept (constant term) of a linear model in context",
    "level": "HOTS"
   },
   {
    "id": "A.ST.1.h",
    "text": "analyze relationships between two quantitative variables revealed in a scatterplot",
    "level": "HOTS"
   },
   {
    "id": "A.ST.1.i",
    "text": "make conclusions based on the analysis of a set of bivariate data and communicate the results",
    "level": "HOTS"
   }
  ]
 }
};
  var SKILL = {};
  Object.keys(STANDARDS).forEach(function (code) { STANDARDS[code].skills.forEach(function (s) { SKILL[s.id] = { code: code, text: s.text, level: s.level }; }); });
  var api = { STANDARDS: STANDARDS, SKILL: SKILL };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  if (root) root.SolStandards = api;
})(typeof window !== "undefined" ? window : (typeof globalThis !== "undefined" ? globalThis : this));
